#!/bin/sh
if [ -d "./ostree-repo" ]; then
    ostree --repo=./ostree-repo prune \
        --keep-younger-than='1 week ago' --refs-only
fi
rpm-ostree-toolbox treecompose -c aos-ci/config/ostree/config.ini \
                --ostreerepo ./ostree-repo
