#!/bin/sh

base_dir="$(dirname $0)/.."

for v in ostree; do
    rsync --delete --stats -a fedora-atomic@artifacts.ci.centos.org::fedora-atomic/${BUILD}/${v}/ ${v}/
done

if [[ ! -e ./ostree ]]; then
    mkdir ostree
    ostree --repo=ostree init --mode=archive-z2
fi

ostree --repo=./ostree prune \
    --keep-younger-than='1 week ago' --refs-only

# get list of repos
# eventually we will be passed the list from the rpm build job
repos=$(rsync fedora-atomic@artifacts.ci.centos.org::fedora-atomic/${BUILD}/repo/ | awk '/^d/ { if ($5 != ".") print $5 }')

f_repos=""
for repo in $repos; do
    if [ -z "$f_repos" ];then
        f_repos="\"${repo}\""
    else
        f_repos="$f_repos, \"${repo}\""
    fi
    cat << EOF > $base_dir/config/ostree/${repo}.repo
[${repo}]
name=Testing ${repo}
baseurl=http://artifacts.ci.centos.org/fedora-atomic/${BUILD}/repo/${repo}
enabled=1
gpgcheck=0
skip_if_unavailable=False
EOF
done

cat << EOF > $base_dir/config/ostree/fedora-atomic-testing.json
{
    "include": "fedora-atomic-testing-docker-host.json",
    "repos": ["fedora-rawhide", $f_repos]
}
EOF

sudo rpm-ostree-toolbox treecompose -c $base_dir/config/ostree/config.ini \
                --ostreerepo ./ostree || exit 1

ostree --repo=./ostree summary -u

if ostree --repo=ostree rev-parse fedora/rawhide/x86_64/atomic-host^ >/dev/null 2>&1; then
    package_diff=$(rpm-ostree db --repo=ostree diff fedora/rawhide/x86_64/atomic-host{^,})
    echo $package_diff
fi

for v in ostree; do
    rsync --delete --stats -a ${v}/ fedora-atomic@artifacts.ci.centos.org::fedora-atomic/${BUILD}/${v}/
done
