#!/bin/bash
set +e

HOMEDIR=$(pwd)
rm -rf ${HOMEDIR}/${fed_repo}/output
mkdir ${HOMEDIR}/${fed_repo}/output
pushd aos-ci/config/Dockerfiles/rpmbuild
# Install docker
which docker
if [ "$?" != 0 ]; then echo "ERROR: DOCKER NOT INSTALLED\nSTATUS: $?"; exit 1; fi
# Only build if it is not built already
if [ "$(docker ps -a | grep rpmbuild-container)" == "" ]; then sudo docker build -t rpmbuild-container . ; fi
sudo docker run --privileged --cap-add=SYS_ADMIN -v ${HOMEDIR}/${fed_repo}/output:/home/${fed_repo}/output -t -i -e fed_repo="${fed_repo}" -e fed_branch="${fed_branch}" -e fed_rev="${fed_rev}" rpmbuild-container
popd
# Find out RSYNC_BRANCH name so we can rsync over an empty repo if it DNE
RSYNC_BRANCH=$(echo ${fed_branch} | sed 's/./&c/1')
if [ "${fed_branch}" = "master" ]; then
    RSYNC_BRANCH=rawhide
fi
mkdir ${RSYNC_BRANCH}
mkdir repo
# Rsync the empty directories over first, then the repo directory
rsync -arv ${RSYNC_BRANCH}/ fedora-atomic@artifacts.ci.centos.org::fedora-atomic
rsync -arv repo/ fedora-atomic@artifacts.ci.centos.org::fedora-atomic/${RSYNC_BRANCH}
rsync --delete --stats -a ${HOMEDIR}/${fed_repo}/output/${fed_repo}_repo fedora-atomic@artifacts.ci.centos.org::fedora-atomic/${RSYNC_BRANCH}/repo
if [ "$?" != 0 ]; then echo "ERROR: RSYNC REPO\nSTATUS: $?"; exit 1; fi
rm -rf ${RSYNC_BRANCH}
rm -rf repo
# Update repo manifest file on artifacts.ci.centos.org
rsync --delete --stats -a fedora-atomic@artifacts.ci.centos.org::fedora-atomic/${RSYNC_BRANCH}/repo/manifest.txt .
# Remove repo name from file if it exists so it isn't there twice
sed -i "/${fed_repo}_repo/d" manifest.txt
echo "${fed_repo}_repo" >> manifest.txt
rsync --delete -stats -a manifest.txt fedora-atomic@artifacts.ci.centos.org::fedora-atomic/${RSYNC_BRANCH}/repo

exit 0
